---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero
  environments_path: "test/integration/environments"
  roles_path: "test/integration/roles"
  data_bags_path: "test/integration/data_bags"
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
#  client_rb:
#     environment: localdev
platforms:
  - name: chef12
    driver:
      customize:
        memory: 2048
        cpus: 2
      vm_hostname: default-chef12
      box: oel71-default
    transport:
      max_ssh_sessions: 1
    provisioner:
      require_chef_omnibus: 12.19.36
suites:
  - name: docker
    run_list:
      - role[curator-applog]
      - role[curator-galactus]
      - recipe[curator_kitchen_helper::uek4]
      - recipe[curator_kitchen_helper::docker]
      - recipe[omc_curator::default]
    verifier:
      inspec_tests:
        - path: test/integration/default/default_spec.rb
